In [1]:
import numpy as np

In [2]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
a[4,:]

array([20, 21, 22, 23, 24])

In [4]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [5]:
a[1::2,0::2]

array([[ 5,  7,  9],
       [15, 17, 19]])

In [6]:
a[1::2,0:3:2]

array([[ 5,  7],
       [15, 17]])

In [7]:
a[:,1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [8]:
a[4]

array([20, 21, 22, 23, 24])

In [9]:
a[-1]

array([20, 21, 22, 23, 24])

In [10]:
a=np.array([20,21,22,23,24])
a

array([20, 21, 22, 23, 24])

In [11]:
a[2:4]

array([22, 23])

In [12]:
a[1::2]

array([21, 23])

In [13]:
a[1::3]

array([21, 24])

In [14]:
b=a[2:4]
b

array([22, 23])

In [15]:
b[0]=10
print(a)
print(b)

[20 21 10 23 24]
[10 23]


In [16]:
c=a[2:4].copy()
c

array([10, 23])

In [17]:
c[0]=1000
print(c)
print(a)

[1000   23]
[20 21 10 23 24]


# Next

In [18]:
a=np.array([0,99,99,30,40,99,60,70])
mask=np.array([0,1,1,0,0,1,0,0],dtype=bool)
print(a)
print(mask)

[ 0 99 99 30 40 99 60 70]
[False  True  True False False  True False False]


In [19]:
a[mask]

array([99, 99, 99])

In [20]:
z=a[mask]
z

array([99, 99, 99])

In [21]:
z[0]=1
z

array([ 1, 99, 99])

In [22]:
a

array([ 0, 99, 99, 30, 40, 99, 60, 70])

In [23]:
a>=90

array([False,  True,  True, False, False,  True, False, False])

In [24]:
a[a>=90]

array([99, 99, 99])

In [25]:
t=np.arange(25).reshape(5,5)
t

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
rows=[0,1,2,3]
cols=[1,2,3,4]
t[rows,cols]

array([ 1,  7, 13, 19])

In [27]:
list(zip(rows,cols))

[(0, 1), (1, 2), (2, 3), (3, 4)]

In [28]:
t

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
t>20

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [30]:
t[t>20]

array([21, 22, 23, 24])

In [31]:
t==4

array([[False, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [32]:
t%3

array([[0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0],
       [1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1],
       [2, 0, 1, 2, 0]], dtype=int32)

In [33]:
t%3==0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]])

In [34]:
#or 
mask = t%3==0
t[mask]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [35]:
mask.dtype

dtype('bool')

In [36]:
mask.shape

(5, 5)

In [37]:
p=np.array([[1,2,3,4],[5,6,7,8]])
p

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
p.sum()

36

In [39]:
p.sum(axis=0)

array([ 6,  8, 10, 12])

In [40]:
p.sum(axis=1)

array([10, 26])

In [41]:
np.sum(p,axis=0)

array([ 6,  8, 10, 12])

In [42]:
np.sum(p,axis=1)

array([10, 26])

o Mathematical Function
+ sum, prod
+ min,max,argmin,argmax
+ ptp(max-min)

o Statistics
+ mean,std,var

o Truth value testing
+ any,all


In [43]:
print(p.shape)
print(p.sum(axis=1))
print(p.mean())
print(p.max())
print(p.max(axis=0))
print(p.min())
print(p.argmin())
print(p.max())
print(p.argmax())

(2, 4)
[10 26]
4.5
8
[5 6 7 8]
1
0
8
7


In [44]:
np.unravel_index(6,p.shape)

(1, 2)

In [45]:
np.unravel_index(p.argmin(),p.shape)

(0, 0)

In [46]:
np.unravel_index(p.argmin(),p.shape)

(0, 0)

In [47]:
np.unravel_index(p.argmax(),p.shape)

(1, 3)

In [48]:
s=np.arange(-2,2)**2
s

array([4, 1, 0, 1], dtype=int32)

In [49]:
s%2==0

array([ True, False,  True, False])

In [50]:
mask= s%2==0
mask

array([ True, False,  True, False])

In [51]:
s[mask]

array([4, 0], dtype=int32)

In [52]:
np.where(mask)

(array([0, 2], dtype=int64),)

In [53]:
positive=np.arange(4)
negative=- positive
print(positive)
print(negative)

[0 1 2 3]
[ 0 -1 -2 -3]


In [54]:
mask

array([ True, False,  True, False])

In [55]:
np.where(mask,positive,negative)

array([ 0, -1,  2, -3])

In [56]:
np.where(mask,positive,99)

array([ 0, 99,  2, 99])

In [57]:
np.where(mask,-99,negative)

array([-99,  -1, -99,  -3])