In [1]:
import numpy as np

In [2]:
l=[0,1,2,3]
l2=[5,6,7,8]
l3=['a','b','c','d']
print(l,l2,l3)
print(type(l),type(l2),type(l3))

[0, 1, 2, 3] [5, 6, 7, 8] ['a', 'b', 'c', 'd']
<class 'list'> <class 'list'> <class 'list'>


In [3]:
a=np.array([0,1,2,3])
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)
print(a.itemsize)
print(a.size)
print(a.nbytes)

[0 1 2 3]
<class 'numpy.ndarray'>
int32
1
4
4
16


In [4]:
l.append(100)
print(l)

[0, 1, 2, 3, 100]


In [5]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
print(a-b)
print(a+b)
print(a*b)
print(a**b)

[-1 -1 -1 -1]
[3 5 7 9]
[ 2  6 12 20]
[   1    8   81 1024]


In [6]:
a=[1,2,3,4]
b=[3,4,3,4]
for n,m in zip(a,b):
    print(n+m)

4
6
6
8


In [7]:
c=[n+m for n,m in zip(a,b)]
print(c)

[4, 6, 6, 8]


In [8]:
t=np.array([0,1,2,3],dtype='int64')
print(t.dtype)
print(t.itemsize)

int64
8


In [9]:
x=np.arange(11)
print(x)

c=(2*np.pi)/10
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10]
0.6283185307179586


In [10]:
x=c*x #x*=c
x

array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])

In [11]:
y=np.sin(x)
y

array([ 0.00000000e+00,  5.87785252e-01,  9.51056516e-01,  9.51056516e-01,
        5.87785252e-01,  1.22464680e-16, -5.87785252e-01, -9.51056516e-01,
       -9.51056516e-01, -5.87785252e-01, -2.44929360e-16])

In [12]:
a=np.array([1,2,3,4])
print(a[0],a[1],a[2])

1 2 3


In [13]:
a[0]=100
a

array([100,   2,   3,   4])

In [14]:
a[1]=11.232 #can't update float value in integer array
a

array([100,  11,   3,   4])

In [15]:
a.fill(-4.5)
a

array([-4, -4, -4, -4])

In [16]:
b=np.array([[0,1,2,3],[10,11,12,13]])
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [17]:
print(b.shape)
print(b.size)
print(b.ndim)

(2, 4)
8
2


In [18]:
b[1,3]

13

In [19]:
b[1,3]=-1
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [20]:
a=np.array([10,11,12,13,14])
a

array([10, 11, 12, 13, 14])

In [21]:
a[1:3]

array([11, 12])

In [22]:
print(a[:3])
print(a[0:3])

[10 11 12]
[10 11 12]


In [23]:
print(a[-2:])

[13 14]


In [24]:
a[::2]

array([10, 12, 14])

In [25]:
a[::3]

array([10, 13])