A Series is used to model one-dimensional data. The Series Object has a few more bits of data, including an index and a name. Series is similar to dictionary.

In [1]:
series={
    'index':[0,1,2,3],
    'data':[145,142,84,23],
    'name':'songs'
}
series

{'index': [0, 1, 2, 3], 'data': [145, 142, 84, 23], 'name': 'songs'}

In [2]:
def get(series,idx):
    value_idx=series['index'].index(idx)
    return series['data'][value_idx]

In [3]:
get(series,1)

142

In [4]:
# examples
songs={
    'index':['Paul','John','George','Ringo'],
    'data':[145,142,38,13],
    'name':'counts'
}
get(songs,'Ringo')

13

# Pandas Series

In [5]:
import pandas as pd #importing library

In [6]:
songs2=pd.Series([1,2,3,4],name='counts')
songs2
# output => ဘယ်ဘက် က index, ညာဘက်က value, name က optional

0    1
1    2
2    3
3    4
Name: counts, dtype: int64

index က string လဲဖြစ်လို့ရတယ်။ 
index က string ဖြစ်နေချိန် index ရဲ့ datatype က string မဟုတ်ပါ။ object datatype ဖြစ်ပါတယ်။

In [7]:
# example
songs3=pd.Series([145,32,5,23],index=['Paul','Jack','George','Ringo'])
songs3

Paul      145
Jack       32
George      5
Ringo      23
dtype: int64

In [8]:
songs3.index

Index(['Paul', 'Jack', 'George', 'Ringo'], dtype='object')

In [9]:
# series လုပ်တဲ့အခါ ဘာ data type မဆိုလုပ်လို့ရတယ်
random=pd.Series(['a','b',True,1.2],name='random')
random

0       a
1       b
2    True
3     1.2
Name: random, dtype: object

In [10]:
random.count()

4

## NaN Value

A series holds numeric values but cannot find a number to represent entry, it will use NaN.
This value stands for Not a Number and is usually ignoredin arithematic operations. 
(Similar to NULL in SQL)

In [11]:
import numpy as np

In [12]:
nan_series=pd.Series([2,np.nan],index=['a','b'])
nan_series

a    2.0
b    NaN
dtype: float64

In [13]:
nan_series.count()

1

In [14]:
nan_series.size

2

In [15]:
#တခုမှတ်ထားရမှာက int64 မှာဆိုရင် NaN လို့မပေါ်ဘူး။ <NA> လို့ပဲပေါ်ပါတယ်။

In [16]:
nan_series2=pd.Series([2,np.nan],index=['a','b'],dtype='Int64')
nan_series2

a       2
b    <NA>
dtype: Int64

In [17]:
# convert data type
nan_series2.astype('Float64')

a     2.0
b    <NA>
dtype: Float64

### Similar to Numpy

In [18]:
array=np.array([1,2,3,4,5])
series=pd.Series([1,2,3,4,5])
print(array)
print(series)

[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64


In [19]:
print(array.mean())
print(series.mean())

3.0
3.0


##### Boolean Array

In [20]:
# numpy
array>np.median(array)

array([False, False, False,  True,  True])

In [21]:
array[array>np.median(array)]

array([4, 5])

In [22]:
# pandas
mask=series>series.median()
mask

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [23]:
series[mask]

3    4
4    5
dtype: int64

## Category Data

+ use less memory than strings
+ can perform operations

In [24]:
s=pd.Series(['z','ab','xc','ld','c'],dtype='category')
s

0     z
1    ab
2    xc
3    ld
4     c
dtype: category
Categories (5, object): ['ab', 'c', 'ld', 'xc', 'z']

In [25]:
s.str.upper()

0     Z
1    AB
2    XC
3    LD
4     C
dtype: object